### ISSUE TITLE
nextcloud无法删除文件，无法上传或创建文件

### ISSUE THREAD

**Issue by sea72** [wahyd4/aria2-ariang-x-docker-compose#58]
纯小白一个， 参考了以前的几个issue，问题还是没有解决，迫不得已提个issue。配置都是原始配置。

已做了的尝试：
1，更新代码，获取最近镜像
2，nextcloud下创建envrioment， 更改uid gid=0，nextcloud无法访问，错误502，已等待数分钟
3，root运行docker     sudo docker-compose up
4，参照#44 ，修改文件
       （1）修改/php/etc/php-fpm.conf
       （2）修改/etc/s6.d/php/run
       （3）修改/nginx/conf/nginx.conf

ps/yml文件

version: '2'
  
services:
  nextcloud:
    image: wonderfall/nextcloud
    volumes:
      - ./data/nextcloud:/data:rw
      - ./data:/user-files:rw
      - ./abc:/abc:rw
    restart: always
  aria2:
    image: wahyd4/aria2-ui:nextcloud
    ports:
      - "8000:80"
      - "6800:6800"
      - "8001:443"
    volumes:
      - ./data:/user-files:rw
    # volumes:
    #   - /some_folder:/root/conf/key
    #   - ~/test/aria2.conf:/root/conf/aria2.conf
    environment:
      - DOMAIN=:80
      # - SSL=true
      # - RPC_SECRET=Hello
      # - ARIA2_USER=admin
      # - ARIA2_PWD=password
      # - ENABLE_AUTH=true
    links:
      - nextcloud:file-manager
    restart: always

**Comment by sea72** [comment]
<img width="344" alt="default" src="https://user-images.githubusercontent.com/24682001/51230944-b2fc9100-199c-11e9-8e83-b701435aa8b0.PNG">

**Comment by wahyd4** [comment]
Thanks for your very detail information, I'm definitely going to find some time recently to dig more.

**Comment by sea72** [comment]
> Thanks for your very detail information, I'm definitely going to find some time recently to dig more.

Thank you.
Feeling sorry for troubling you. And i'm tring to solve it.

**Comment by sea72** [comment]
已进一步参照#44
 
1 设置uip gid=0
2 修改/php/etc/php-fpm.conf        /etc/s6.d/php/run       /nginx/conf/nginx.conf  （不知是否需要重启php-fpm）

nextcloud 仍然502

ps
`~ # ps -ef|grep php
   50 root      0:01 s6-supervise php
 2558 root      0:00 php-fpm: master process (/php/etc/php-fpm.conf)
 2559 root      0:00 php-fpm: pool www
 2560 root      0:00 php-fpm: pool www
 2562 root      0:00 grep php

~ # exit
root@curiosity:~/aria2-ariang-x-docker-compose/nextcloud# docker logs -f -t --tail=10 nextcloud_nextcloud_1
2019-01-16T15:35:16.739843391Z [16-Jan-2019 15:35:16] ERROR: [pool www] please specify user and group other than root
2019-01-16T15:35:16.739975077Z [16-Jan-2019 15:35:16] ERROR: FPM initialization failed
2019-01-16T15:35:17.741229541Z [16-Jan-2019 15:35:17] ERROR: [pool www] please specify user and group other than root
2019-01-16T15:35:17.741322478Z [16-Jan-2019 15:35:17] ERROR: FPM initialization failed
2019-01-16T15:35:18.743209550Z [16-Jan-2019 15:35:18] ERROR: [pool www] please specify user and group other than root
2019-01-16T15:35:18.743333969Z [16-Jan-2019 15:35:18] ERROR: FPM initialization failed
2019-01-16T15:35:19.743144449Z [16-Jan-2019 15:35:19] ERROR: [pool www] please specify user and group other than root
2019-01-16T15:35:19.743257329Z [16-Jan-2019 15:35:19] ERROR: FPM initialization failed
2019-01-16T15:35:20.743267087Z [16-Jan-2019 15:35:20] ERROR: [pool www] please specify user and group other than root
2019-01-16T15:35:20.743366007Z [16-Jan-2019 15:35:20] ERROR: FPM initialization failed
`

**Comment by wahyd4** [comment]
Thank you.
 if you have some time, please also jsut try to run the Nextcloud docker image [`wonderfall/nextcloud`](https://github.com/Wonderfall/docker-nextcloud) alone to see if you still have this permission issue or not. This docker image is the same image with what I used in the docker compose file.

To be fair, I tried and I got the same issue.

**Comment by sea72** [comment]
Today, I tried to modify the permisson of "user-files" to 777 , change the owner to 991 . Unluckily still not work.
I think it's beyond my capability for the moment. I'd like to use some alternative scheme.
Sorry for this.

**Comment by wahyd4** [comment]
That's alright, I don't like the nextcloud docker image either. It's really
a plain. By the way, if you don't need a Dropbox thing rather than a file
manager you can just try the aria2 + file manager one, it's just a single
container. Please see the bootom of the readme for the link. Cheers.

**Comment by sea72** [comment]
Nice suggestion. Thank you.

**Comment by wahyd4** [comment]
I would like to reopen it and will try to solve this issue. Maybe I'll try to make a custom Nextcloud docker image.

**Comment by wahyd4** [comment]
@oceanwave72 I think this bug has been fixed from latest commits, would you like a give an another go?
The only thing also the most vital command to run on your host(not inside the docker container) is:
``` bash
chown -R www-data <folder> #The folder you'd like share to the container
```
Also do not forget to pull the latest docker images by:
```
docker-compose pull
```

**Comment by sea72** [comment]
oh, yesterday I installed it again and found that no permissions to mount external storage. I am just wondering what happened.
I'll reinstall it following your instructions tomorrow.  I'll keep you updated.

**Comment by wahyd4** [comment]
You must run the chown -R command to grant read and write access to
www-data user oh your host.

**Comment by sea72** [comment]
@wahyd4    I delete the file and reinstall it . However problem still remain.
On the website , show the following warning.

 **1.  the owner of the file** 
<img width="599" alt="default" src="https://user-images.githubusercontent.com/24682001/51437689-8cac5d80-1cdc-11e9-9e72-300e9f073d29.PNG">

2. the waring on the website
<img width="1019" alt="1" src="https://user-images.githubusercontent.com/24682001/51437718-ddbc5180-1cdc-11e9-89e9-c08c513b9bd0.PNG">

3. i am the admin of the nextcloud
<img width="313" alt="2" src="https://user-images.githubusercontent.com/24682001/51437721-f88ec600-1cdc-11e9-9217-3313152ed0c8.PNG">


Thanks for your efforts. Wait for your reply.

**Comment by wahyd4** [comment]
So this is not an issue it's just because you didn't find the correct menu.
On the settings pages there are two external storage links. I think you
clicked the wrong one, please click the one at the bottom. That's the
global link for configuring he storage.

**Comment by sea72** [comment]
@wahyd4  Many thanks for your patient help. I've solve this finally.

**Comment by sea72** [comment]
@wahyd4  By the way , i found the readme.md in nextcoud is a little different with the one of main page.
`- /data/nextcloud:/data`     VERSUS      `- ./data/nextcloud:/data`
A symbol "." seems to be lost. I am not sure if this represent the absolute path and relative path.
Thank you again. The appreciation is beyond my words.

**Comment by wahyd4** [comment]
I'll double check, thank you.

**Comment by wahyd4** [comment]
@oceanwave72  whether to have `.` doesn't matter,  it means different folder, as long as you can access those folders, then that's all good

**Comment by sea72** [comment]
I found that the command needs to be executed after downloading new files. So I set a crontab task.

**Comment by wahyd4** [comment]
That shouldn't be the case. Maybe because the chown has been applied to the
sub folders.
